<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<%--This is the standard Java tag library--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<%--We import the JSTL Formater to use to format the date--%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<%--We add here the Spring tags library which will be used for our form--%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>


<c:url var="loginUrl" value="/login"/>

<%--Here we display any errors on login--%>
<c:if test="${param.error != null}">
    <div class="alert alert-danger alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong> LOGIN FAILED.</strong>
        Incorrect username or password.
    </div>
</c:if>

<div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">

        <div class="panel panel-default">

            <div class="panel-heading">

                <div class="panel-title">Login</div>

            </div>


            <div class="panel-body">

                <form method="post" class="login-form" action="${loginUrl}">

                    <%--Cross Site Request Forgery field - This is a random token generated by Spring to prevent
                    some hacking on our login page. This needs to be submitted with our login credentials.--%>
                    <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}">

                    <div class="input-group">
                        <input type="text" name="username" placeholder="Username" class="form-control"/>
                    </div>

                    <div class="input-group">
                        <input type="password" name="password" placeholder="Password" class="form-control"/>
                    </div>

                    <div class="input-group">
                        <button type="submit" class="btn btn-success pull-right"> Sign in</button>
                    </div>

                </form>

            </div>
        </div>

    </div>

    <%--
        &lt;%&ndash;This is the Script for TinyMCE &ndash;%&gt;
        <script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
        <script>
            tinymce.init({
                selector: 'textarea',
                plugins: "link"
            });
        </script>--%>
